DELETE FROM likes;
DELETE FROM friends;
DELETE FROM films_genres;
DELETE FROM films;
DELETE FROM users;

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE films ALTER COLUMN id RESTART WITH 1;